# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

before_install:
- sudo apt-get update -qq
- sudo apt-get install aptitude 
- sudo aptitude install gdal-bin libgdal-dev libgdal1-dev libproj-dev libgdal1h -y
- sudo apt-get install libcurl4-openssl-dev
- Rscript -e 'install.packages("rgdal")'

r_binary_packages:
- soilDB
- sp
- raster
- RCurl

r_github_packages:
- omegahat/SSOAP
- omegahat/xmlschema
- benmarwick/FedData

# after_success:

notifications:
email:
on_success: change
on_failure: change
