# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install aptitude 
  - sudo aptitude install libgdal-dev -y
  - sudo aptitude install libproj-dev -y
  - sudo apt-get install libgdal1-dev libproj-dev libcurl4-gnutls-dev

install:
  - ./travis-tool.sh install_aptget r-cran-rgdal r-cran-rgeos r-cran-soilDB r-cran-sp r-cran-raster r-cran-rcurl
  - ./travis-tool.sh install_github benmarwick/FedData
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

