# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

before_install:
- sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get update -qq
- sudo apt-get install aptitude 
- sudo aptitude install gdal-bin libgdal-dev libgdal1-dev libproj-dev libgdal1h -y
- sudo apt-get install libcurl4-openssl-dev

r_binary_packages:
- rgdal
- soilDB
- sp
- raster
- RCurl

r_github_packages:
- omegahat/SSOAP
- omegahat/xmlschema
- benmarwick/FedData

# after_success:

notifications:
email:
on_success: change
on_failure: change
