# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

before_install:
- sudo apt-get install aptitude 
- sudo aptitude install gdal-bin libgdal-dev libgdal1-dev libproj-dev libgdal1h -y
- sudo apt-get install libcurl-dev

r_binary_packages:
- rgdal
- soilDB
- sp
- raster
- RCurl
- SSOAP
- XMLSchema

r_github_packages:
- benmarwick/FedData

# after_success:

notifications:
email:
on_success: change
on_failure: change
