# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

before_install:
- sudo apt-get install aptitude 
- sudo aptitude install libgdal-dev -y
- sudo aptitude install libproj-dev -y
- sudo aptitude install libgeos-dev -y
- sudo apt-get install libcurl4-gnutls-dev

r_binary_packages:
- rgdal
- rgeos
- soilDB
- sp
- raster
- RCurl

r_github_packages:
- benmarwick/FedData

# after_success:

notifications:
email:
on_success: change
on_failure: change
